---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gitpod-issuer
  namespace: default
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: $PROJECT_NAME
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-certificates
  namespace: default
spec:
  secretName: https-certificates
  issuerRef:
    name: gitpod-issuer
    kind: Issuer
  dnsNames:
    - $DOMAIN
    - "*.$DOMAIN"
    - "*.ws.$DOMAIN"
